[IN PROGRESS] Update tx structure
radixdlt/app-radix pull request #11
Opened 2021-06-30 12:13 UTC by Sajjon

2021-06-30 14:02 UTC, Sajjon commented on src/transaction/transaction_parser.c
> +static bool update_tx_fee_and_total_xrd_cost_if_needed(re_ins_syscall_t *syscall,
@siy this function is new and probably the most notable and important update of this entire PR. It changes how tx fee is calculated.

2021-06-30 15:54 UTC, Sajjon commented
Status: I think implementation wise it is ready to be merged.

I would probably test with some "real world" transactions first. I.e. wait for when this version can be used with Radix Wallet.

@siy so make a very temporary build, `bin`and `debug` folders zipped and send over Slack or something to @AbstractFruitFactory and maybe Caleb at Township so they can test it. Or of they give you a Radiw Wallet which points to a network supporting this new TX structure. Would be great to test those real world transactions before merging this PR.

Good luck!

2021-07-16 16:20 UTC, iamyulong approved these changes
LGTM

2021-07-16 17:12 UTC, talekhinezh requested changes

2021-07-16 17:12 UTC, talekhinezh commented on src/instruction/instruction.c
> +            return false;  // should never happen
Can we exit() with error rather than failing silently in these cases?

2021-07-16 17:12 UTC, talekhinezh commented on src/instruction/instruction.h
> +    substate_t substate;
vreads are now encoded differently from before. They are a different structure compared to substates and in general will only contain a key (for example only the validator key for AllowDelegationFlag).

2021-07-16 17:12 UTC, talekhinezh commented on src/transaction/transaction_parser.c
> +               &transaction->total_xrd_amount_incl_fee);
Looks very scary having the same pointer to source and target. Can we confirm for sure that in place updates will work for all values?

2021-07-16 17:12 UTC, talekhinezh commented on src/transaction/transaction_parser.c
> +        minus256(&transaction->tx_fee, &amount, &transaction->tx_fee);
Same comment regarding in place updates.

2021-07-16 17:12 UTC, talekhinezh commented on src/transaction/transaction_parser.c
> +                 &transaction->total_xrd_amount_incl_fee);
More in place updates

2021-07-16 17:12 UTC, talekhinezh commented on src/types/uint256.c
> +    clear256(&zero);
surely we can do better than using zero buffers :)

2021-07-19 14:03 UTC, merged